advertising_msg: "
&cДарова! \n
Я приглашаю тебя в {town_name} \n
Я - {mayor_name} \n
Город находиться в {nation_name} \n
Наш бюджет {coffers} \n
И нас около {population_amount} \n

{join_btn}
"
join_btn: "&cПрисоединиться"

advertising_price: 200
advertising_delay: 10


vk_api_key: "" #Получить можно, перейдя по этой ссылке https://oauth.vk.com/authorize?client_id=8014426%3Capp_id%3E&redirect_uri=https://oauth.vk.com/blank.html&display=page&scope=wall&response_type=token&v=5.130
group_id: "196516553" #айди группы

advertising_msg_vk: "
Дарова! \n
Я приглашаю тебя в {town_name} \n
Я - {mayor_name} \n
Город находиться в {nation_name} \n
Наш бюджет {coffers} \n
И нас около {population_amount} \n
"